{{- if .Values.imagePullSecretContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.imagePullSecrets 0).name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecretContent }}
{{- end }}
