{{- if .Values.envSecretContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.envSecretContent }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
